version: "3"
volumes:
  tmpdir:
    driver: local
    driver_opts:
      type: tmpfs
      o: "size=512m"
      device: ":/tmp"
services:
  canary:
    container_name: autograph-canary
    image: autograph-canary
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CANARY_LOG_LEVEL=debug
    volumes:
      - tmpdir:/tmp/

  emulator:
    container_name: autograph-canary-lambda-emulator
    image: autograph-canary-lambda-emulator
    build:
      context: .
      dockerfile: Dockerfile.lambda-emulator
    volumes:
      - tmpdir:/tmp/
    ports:
      - "9000:8080"
